### ISSUE TITLE
Proposed experiments

### ISSUE THREAD

**Issue by navidcy** [dhruvbhagtani/sfc-perturbation-expts#2]
Before writing everything in README let's first discuss everything in an issue or in a discussion. Or over a PR even! And when we feel it's cooked you merge and move on? 

That's the whole idea of doing it in Github, right? Think it'll be more fun this way.

**Comment by dhruvbhagtani** [comment]
Yes, we can open issues/discussions for each experiment. But I felt it'll be nice to have everything at one place, and we can add/remove experiments as we see fit. The readme is just a rough idea on the different experiments we could try out.

**Comment by navidcy** [comment]
Sure. The `README` is a good starting point.

Let's not have a separate issue for each experiment for now as we want to discuss about all experiments and what to do or not. I'll start a discussion.

cc @AndyHoggANU @rmholmes

**Comment by navidcy** [comment]
Closing this in favor of #4.
