### ISSUE TITLE
Should we make a GitHub pages website?

### ISSUE THREAD

**Issue by dhruvbhagtani** [dhruvbhagtani/sfc-perturbation-expts#5]
Is it too early, or should we do it now? It'll be easier to write everything in there, rather than in Readme file.

**Comment by AndyHoggANU** [comment]
Not sure how this would look - but I like the idea of some Discussion pages? Or project boards?

**Comment by dhruvbhagtani** [comment]
I haven't worked with either, so I am open to both. I'll try to make some headway on these.

**Comment by navidcy** [comment]
I also feel the Discussions, Projects, and Issues will work well. No need for over-engineering.
