### ISSUE TITLE
Capability to do wind-masked experiments at 1° resolution

### ISSUE THREAD

**Issue by AndyHoggANU** [dhruvbhagtani/sfc-perturbation-expts#6]

**Comment by rmholmes** [comment]
Requires:
1. Creation of netcdf `wind_mask.nc` file.
2. Implementation of resolved shear parameterization.
3. A new control run.

Anything else?

I have a relatively up to date 1-degree RYF control run here `/scratch/e14/rmh561/access-om2/archive/1deg_jra55v14_ryf_rcpcont/` for tuning your parameterization. I'm not 100% sure it has all the variables you need.

**Comment by dhruvbhagtani** [comment]
Thanks Ryan, I'll use this. Although, can I access `e14`, since I am not a part of it now?

**Comment by dhruvbhagtani** [comment]
Plot is the fractional difference between control and parameterised KPP run with the exact same parameters as 0.25 model; they show that our resolved shear parameterisation performs well. However, there are blobs in the North Pacific and Atlantic, hinting towards erroneous calculations of the resolved shear in these regions. The next step is to rerun the 1 degree model, this time varying the exponential function. Initial tests show that the exponential coefficient needs to be reduced from 0.01 to 0.0025-0.004, but an optimal parameter can only be obtained after running the experiment.

<img width="1183" alt="Screen Shot 2021-10-07 at 8 03 10 pm" src="https://user-images.githubusercontent.com/29700296/136406089-2db84638-062f-45ff-a642-9a285c11b970.png">

**Comment by dhruvbhagtani** [comment]
We can either leave the parameterisation as it is, just for the sake of consistency between models. Or we could hunt for a more optimal resolved shear parameterisation. Basically, the result from the 0.25 degree run were also similar, they also showed these similar blobs. So I think we can use the exact same parameterisation. What do you say?

**Comment by dhruvbhagtani** [comment]
I am inclined towards staying with the same coefficients as 0.25 degree model, and instead working on making a new mask for our 1 degree run.

**Comment by AndyHoggANU** [comment]
OK, I agree the resolved shear is not too bad. I guess the check is that, once you improve the exponential function, do you end up with a similar mean climate to the original simulation? So , I agree you should go ahead as is.

**Comment by rmholmes** [comment]
Sounds good to me.

I would suggest you clone the latest from https://github.com/COSIMA/1deg_jra55_ryf and make your modifications from there. Even though this is a 1-degree one, I think it is still worth looking at the diagnostic table and commenting out what you don't think you'll need. The spin-up/s will be long so you won't need everything and can always turn things on later in the run. I'm happy to check your `diag_table` if you'd like input.

**Comment by dhruvbhagtani** [comment]
Okay, just for my sanity, I ran the 1 degree experiment for `48 hours` model time with `exp_coeff = 0.004`, and didn't find much difference on the whole. The blobs in the North Atlantic and North Pacific do reduce, along with the Weddell gyre blob too (see the above figure), but it happens at the cost of the tropical and subtropical regions, which now show a large error. So, I'll stick with the `exp_coeff = 0.01`. So, we don't need to run the `exp_coeff = 0.004` case for longer to check whether we get a similar mean climate as the original simulation or not.

@rmholmes I forgot to tell, I haven't used your simulation yet, I made my own as I needed some hourly snap results to compare KPP depths. Now I'll need them. I think I'll have to make my executable again, as the atmosphere version you are using may not be what is present in the latest `1deg_jra55_ryf` repository, and ideally, we would like our simulations to be consistent. 

Yes, now that I've got (a little) experience with running models, I can think of many diagnostics I won't need. So I'll comment out those and post it on GitHub for you to have a look.

**Comment by rmholmes** [comment]
Do you think 48 hours is long enough to be confident with the results? I would have thought you'd need a longer run.

Fair enough. However, again are you confident that you have run long enough for you test to be sufficient?

That run I sent you did use JRA55 v1.4 (not 1.3), which is the same as the latest version in https://github.com/COSIMA/1deg_jra55_ryf

**Comment by dhruvbhagtani** [comment]
Yeah, maybe 48 hours isn't really enough. Let me run both the runs longer and see how they go.

**Comment by dhruvbhagtani** [comment]
Also, here are the diagnostics I removed from config files:
https://github.com/COSIMA/1deg_jra55_ryf/compare/master...dhruvbhagtani:nostress?expand=1

I think I can remove more, but I don't understand what some of the variables do, and to be safe, didn't remove them.

**Comment by dhruvbhagtani** [comment]
Btw, @rmholmes, your outputs don't contain `hblt`, which is the diagnostic I have to compare. So, should I run the control (without resolved shear parameterisation) run for some time, say 10 years?

**Comment by rmholmes** [comment]
I did a PR for the diagnostics.

This is the one-degree model. It is super cheap and fast. So yes, definitely run for 10 years!
